### ISSUE TITLE
train.py is missing

### ISSUE THREAD

**Issue by larryzhz** [chadwick-yao/KUKA-Controller#1]
train.py is missing, thanks a lot.

**Comment by chadwick-yao** [comment]
Thank you for your attention and reminder. The code for this training uses diffusion policy, which is not included in this repository. I will make some modifications to the code and README this week.

**Comment by larryzhz** [comment]
Wish your latest updates  come out ASAP, very much!

**Comment by chadwick-yao** [comment]
I've already updated this repo. Feel free to ask any questions.
