### ISSUE TITLE
UR5

### ISSUE THREAD

**Issue by Nimingez** [chadwick-yao/KUKA-Controller#2]
I want to control UR5, what should i do?

**Comment by chadwick-yao** [comment]
Actually, <a href="https://github.com/real-stanford/diffusion_policy/tree/548a52bbb105518058e27bf34dcf90bf6f73681a">diffusion policy</a> works on UR5. And I just applied it on KUKA based on their code. You can review that repo.

**Comment by Nimingez** [comment]
I can not link my spacemouse
